require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MarinasController do

  # This should return the minimal set of attributes required to create a valid
  # Marina. As you add validations to Marina, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MarinasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all marinas as @marinas" do
      marina = Marina.create! valid_attributes
      get :index, {}, valid_session
      assigns(:marinas).should eq([marina])
    end
  end

  describe "GET show" do
    it "assigns the requested marina as @marina" do
      marina = Marina.create! valid_attributes
      get :show, {:id => marina.to_param}, valid_session
      assigns(:marina).should eq(marina)
    end
  end

  describe "GET new" do
    it "assigns a new marina as @marina" do
      get :new, {}, valid_session
      assigns(:marina).should be_a_new(Marina)
    end
  end

  describe "GET edit" do
    it "assigns the requested marina as @marina" do
      marina = Marina.create! valid_attributes
      get :edit, {:id => marina.to_param}, valid_session
      assigns(:marina).should eq(marina)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Marina" do
        expect {
          post :create, {:marina => valid_attributes}, valid_session
        }.to change(Marina, :count).by(1)
      end

      it "assigns a newly created marina as @marina" do
        post :create, {:marina => valid_attributes}, valid_session
        assigns(:marina).should be_a(Marina)
        assigns(:marina).should be_persisted
      end

      it "redirects to the created marina" do
        post :create, {:marina => valid_attributes}, valid_session
        response.should redirect_to(Marina.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved marina as @marina" do
        # Trigger the behavior that occurs when invalid params are submitted
        Marina.any_instance.stub(:save).and_return(false)
        post :create, {:marina => {}}, valid_session
        assigns(:marina).should be_a_new(Marina)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Marina.any_instance.stub(:save).and_return(false)
        post :create, {:marina => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested marina" do
        marina = Marina.create! valid_attributes
        # Assuming there are no other marinas in the database, this
        # specifies that the Marina created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Marina.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => marina.to_param, :marina => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested marina as @marina" do
        marina = Marina.create! valid_attributes
        put :update, {:id => marina.to_param, :marina => valid_attributes}, valid_session
        assigns(:marina).should eq(marina)
      end

      it "redirects to the marina" do
        marina = Marina.create! valid_attributes
        put :update, {:id => marina.to_param, :marina => valid_attributes}, valid_session
        response.should redirect_to(marina)
      end
    end

    describe "with invalid params" do
      it "assigns the marina as @marina" do
        marina = Marina.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Marina.any_instance.stub(:save).and_return(false)
        put :update, {:id => marina.to_param, :marina => {}}, valid_session
        assigns(:marina).should eq(marina)
      end

      it "re-renders the 'edit' template" do
        marina = Marina.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Marina.any_instance.stub(:save).and_return(false)
        put :update, {:id => marina.to_param, :marina => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested marina" do
      marina = Marina.create! valid_attributes
      expect {
        delete :destroy, {:id => marina.to_param}, valid_session
      }.to change(Marina, :count).by(-1)
    end

    it "redirects to the marinas list" do
      marina = Marina.create! valid_attributes
      delete :destroy, {:id => marina.to_param}, valid_session
      response.should redirect_to(marinas_url)
    end
  end

end
